import { GetStaticPaths, GetStaticProps } from 'next'
import { getTopic, getTopicArticles, getTopicSlugs } from '../../utils/articles'
import Head from 'next/head'
import { ArticleList } from '../../components/ArticleList'
import { ArticleInterface } from '../../types/article.types'

export default function Topic({
  articlesData,
  topic,
}: {
  articlesData: ArticleInterface[]
  topic: {
    name: string
    cssClass: string
    slug: string
  }
}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ArticleList articles={articlesData} topic={topic} />
    </div>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = getTopicSlugs()
  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const articlesData = await getTopicArticles(params?.slug as string)
  const topic = getTopic(params?.slug as string)

  return {
    props: {
      articlesData,
      topic,
    },
  }
}
