import { GetStaticPaths, GetStaticProps } from 'next'
import {
  getAllArticleSlugs,
  getTopicArticles,
  getTopicSlugs,
} from '../../utils/articles'
import Head from 'next/head'
import Link from 'next/link'

export default function Topic({
  articlesData,
}: {
  articlesData: {
    date: string
    title: string
    id: string
  }[]
}) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Hello there I am HOMEPAGE!</div>

      <ul>
        {articlesData.map(({ id, date, title }) => (
          <li key={id}>
            <Link href={`/articles/${id}`}>
              <a>{title}</a>
            </Link>
            <br />
            <p>{date} </p>
          </li>
        ))}
      </ul>
    </div>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = getTopicSlugs()
  return {
    paths,
    fallback: false,
  }
}

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const articlesData = await getTopicArticles(params?.slug as string)

  console.log('articlesdata', articlesData)

  return {
    props: {
      articlesData,
    },
  }
}
