import { GetStaticProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import Layout from '../components/Layout'
import { getSortedArticlesData } from '../utils/articles'

export default function Home({
	allArticlesData,
}: {
	allArticlesData: {
		date: string
		title: string
		id: string
	}[]
}) {
	return (
		<Layout home>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div>Hello there I am HOMEPAGE!</div>

			<ul>
				{allArticlesData.map(({ id, date, title }) => (
					<li key={id}>
						<Link href={`/articles/${id}`}>
							<a>{title}</a>
						</Link>
						<br />
						<p>{date} </p>
					</li>
				))}
			</ul>
		</Layout>
	)
}

export const getStaticProps: GetStaticProps = async () => {
	const allArticlesData = getSortedArticlesData()
	return {
		props: {
			allArticlesData,
		},
	}
}
