import { GetStaticProps } from 'next'
import Head from 'next/head'

import { getSortedArticlesData } from '../utils/articles'
import { Hero } from '../components/Hero'
import { ArticleList } from '../components/ArticleList'
import { ArticleInterface } from '../types/article.types'

export default function Home({
  allArticlesData,
}: {
  allArticlesData: ArticleInterface[]
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      {allArticlesData && (
        <ArticleList
          articles={allArticlesData}
          topic={{ name: 'All', slug: 'all', cssClass: 'all' }}
        />
      )}
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const allArticlesData = getSortedArticlesData()

  return {
    props: {
      allArticlesData,
    },
  }
}
